version: '3'
services: 
  backend:
    build: 
      context: .
    ports: 
      - '8080:80'
    depends_on:
      database:
        condition: service_healthy


  database:
    image: postgres:15.2-alpine3.17
    environment:
      POSTGRES_PASSWORD: C0mp4ny!fx
      POSTGRES_DB: lavyn
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
